_format_version: "2.1"

services:
  - name: jeo-services
    url: http://server
    tags:
      - wanda
    routes:
      - name: service-private-route
        paths:
          - /
#    plugins:
#      - name: key-auth

plugins:
  - name: session
    route: service-private-route
    config:
      secret: alagrandelepusecuca
      storage: cookie
      cookie_secure: false

consumers:
  - username: default-user
    custom_id: "1"
    keyauth_credentials:
      - key: a754766ed1b1