version: '3.5'

networks:
  jeo:
    external: false

services:
  mongo:
    image: "mongo:4.0"
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    restart: always
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - jeo